[workspace]
members = [
  "maprox-application",
  "maprox-common",
  "examples/maprox-client",
  "examples/maprox-leptos"
]

resolver = "2"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
