[package]
name = "maprox-leptos"
version = "0.1.0"
edition = "2021"

[dependencies]
matchbox_socket = "0.6.1"
maprox-common = { path = "../../maprox-common" }
flatgeobuf = { version = "3.25.0", default-features = false }
geozero = "0.9.9"

leptos = "0.3"
