[package]
name = "maprox-common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
ciborium = "0.2"
matchbox_socket = "0.6.0"
log = { version = "0.4", default-features = false }
