name: Staging

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  MAPROX_CONNECTION_URL: ${{ secrets.MAPROX_CONNECTION_URL }}

jobs:
  format:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./github/actions/setup
        with:
          target: x86_64-unknown-linux-gnu

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

  native_tests:
    name: Native tests for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          target: x86_64-unknown-linux-gnu
        - os: macos-latest
          target: x86_64-apple-darwin
        - os: windows-latest
          target: x86_64-pc-windows-gnu
    steps:
      - name: Setup
        uses: ./github/actions/setup
        with:
          target: ${{ matrix.target }}

      - name: Run tests
        run: cargo test --target ${{ matrix.target }}

  web_tests:
    name: Web tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [firefox, chrome]
    steps:
      - name: Setup
        uses: ./github/actions/setup
        with:
          target: wasm32-unknown-unknown

      - name: Install wasm-pack and browser
        uses: jetli/wasm-pack-action@v0.4.0

      - name: Installing ${{ matrix.browser }}
        uses: browser-actions/setup-${{ matrix.browser }}@v1

      - name: Run tests
        run: wasm-pack test --headless --${{ matrix.browser }}

  clippy_check:
    name: Lints (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./github/actions/setup
        with:
          target: x86_64-unknown-linux-gnu

      - name: Run clippy
        run: cargo clippy --all-targets -- -D warnings

  coverage:
    name: Code coverage (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./github/actions/setup
        with:
          target: x86_64-unknown-linux-gnu

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.15.0'
      - name: Upload coverage report to codecov.io
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error:     true