# Inspired by: https://github.com/LukeMathWalker/zero-to-production/blob/main/.github/workflows/audit.yml
name: Staging

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-stage-test-${{ hashFiles('**/Cargo.toml') }}
      - name: Install toolchain - nightly
        uses: actions-rs/toolchain@v1
        with:
              toolchain: nightly
              profile: minimal
      - name: Install linker - mold
        run: sudo apt-get update; sudo apt-get install mold
      - name: Install Bevy dependencies
        run: sudo apt-get update; sudo apt-get install pkg-config libx11-dev libasound2-dev libudev-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Run cargo test
        run: cargo test

  format:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install toolchain - nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          components: rustfmt      
      - name: Run cargo fmt
        run: cargo fmt --all -- --check

  clippy_check:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-stage-clippy-${{ hashFiles('**/Cargo.toml') }}
      - name: Install toolchain - nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          components: clippy      
      - name: Install linker - mold
        run: sudo apt-get update; sudo apt-get install mold
      - name: Install Dependencies
        run: sudo apt-get update; sudo apt-get install pkg-config libx11-dev libasound2-dev libudev-dev
      - name: Run clippy
        run: cargo clippy -- -D warnings

  coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    steps:
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-stage-coverage-${{ env.cache-name }}-${{ hashFiles('**/Cargo.toml') }}
      - name: Install toolchain - nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          components: clippy      
      - name: Install Dependencies
        run: sudo apt-get update; sudo apt-get install pkg-config libx11-dev libasound2-dev libudev-dev
      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin
      - name: Run tarpaulin
        run: cargo tarpaulin --verbose --ignore-tests