name: Deploy maprox-demo.

env:
  CARGO_TERM_COLOR: always
  MAPROX_CONNECTION_URL: ${{ secrets.MAPROX_CONNECTION_URL }}

on:
  workflow_run:
    workflows: ["Staging"]
    branches: [main]
    types: 
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-stage-test-${{ hashFiles('**/Cargo.toml') }}
      - name: Install toolchain - nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
      - name: Install linker - mold
        run: sudo apt-get update; sudo apt-get install mold
      - name: Install Bevy dependencies
        run: sudo apt-get update; sudo apt-get install pkg-config libx11-dev libasound2-dev libudev-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libwayland-dev libxkbcommon-dev
      - name: Add wasm32 target
        run: rustup target add wasm32-unknown-unknown     
      - name: Install/Update Trunk
        run: which trunk 2>/dev/null || cargo install trunk
      - name: Bundle demo
        run: ./scripts/bundle_demo.sh
      - name: Configure Github Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
